test:
  stage: test
  image:
    name: node:13.10.1
  services:
    - postgres:11.6
  script:
    - yarn
    - yarn test

lint:
  stage: test
  image:
    name: node:13.10.1
  script:
    - yarn
    - yarn lint
